title: AGF
description: "Scripts or Descriptions for Chapters in the \"Age and Growth of Fishes: Principles and Techniques\" Book"
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
